[package]
name = "ip-watch"
version = "0.1.0"
authors = ["Parity Technologies Limited <admin@parity.io>"]
edition = "2018"
keywords = ["asynchronous", "routing"]

[dependencies]
libc = "0.2.66"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.8", features = ["netioapi", "ntdef", "ws2def"] }
