[package]
name = "if-watch"
version = "0.1.4"
authors = ["David Craven <david@craven.ch>", "Parity Technologies Limited <admin@parity.io>"]
edition = "2018"
keywords = ["asynchronous", "routing"]
license = "MIT OR Apache-2.0"
description = "crossplatform asynchronous network watcher"
repository = "https://github.com/dvc94ch/if-watch"

[dependencies]
futures-lite = "1.11.2"
ipnet = "2.3.0"
libc = "0.2.66"
log = "0.4.11"

[target.'cfg(unix)'.dependencies]
async-io = "1.2.0"

[target.'cfg(windows)'.dependencies]
futures = { version = "0.3.8", default-features = false }
if-addrs = "0.6.5"
winapi = { version = "0.3.8", features = ["netioapi", "ntdef", "winerror", "ws2def"] }

[dev-dependencies]
env_logger = "0.8.1"
